-- Run this in Supabase SQL Editor: https://supabase.com/dashboard
-- Fresh install: run the full file. Existing DB: run supabase/migrations/002_student_accounts.sql

-- Students (created when a student registers; linked to auth.users)
create table if not exists public.students (
  id bigint generated by default as identity primary key,
  user_id uuid unique references auth.users(id) on delete cascade,
  name text not null,
  matric text not null unique,
  course text not null default 'Computer Science',
  email text,
  status text not null default 'Present' check (status in ('Present', 'Absent', 'Late')),
  created_at timestamptz not null default now()
);

-- Live attendance sessions (teacher starts, students sign in until end)
create table if not exists public.attendance_sessions (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  title text not null,
  course text not null,
  teacher_id uuid not null,
  teacher_name text not null,
  started_at timestamptz not null default now(),
  ends_at timestamptz not null,
  duration_minutes int not null default 15,
  status text not null default 'active' check (status in ('active', 'ended')),
  created_at timestamptz not null default now()
);

-- Attendance records (daily roll; may link to a session)
create table if not exists public.attendance_records (
  id uuid primary key default gen_random_uuid(),
  student_id bigint not null references public.students(id) on delete cascade,
  student_name text not null,
  matric text not null,
  course text,
  status text not null check (status in ('Present', 'Absent', 'Late')),
  date date not null,
  session_id uuid references public.attendance_sessions(id) on delete set null,
  created_at timestamptz not null default now(),
  unique (student_id, date)
);

-- Student sign-ins during a session
create table if not exists public.session_sign_ins (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null references public.attendance_sessions(id) on delete cascade,
  student_id bigint not null references public.students(id) on delete cascade,
  student_name text not null,
  matric text not null,
  status text not null default 'Present' check (status in ('Present', 'Absent', 'Late')),
  signed_at timestamptz not null default now(),
  unique (session_id, student_id)
);

-- Profiles (teachers + students; linked to auth.users)
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  role text not null default 'teacher' check (role in ('teacher', 'student', 'admin')),
  matric text,
  course text,
  student_id bigint references public.students(id) on delete set null,
  created_at timestamptz not null default now()
);

-- Row Level Security
alter table public.students enable row level security;
alter table public.attendance_records enable row level security;
alter table public.profiles enable row level security;
alter table public.attendance_sessions enable row level security;
alter table public.session_sign_ins enable row level security;

create policy "Auth users manage students"
  on public.students for all
  using (auth.role() = 'authenticated')
  with check (auth.role() = 'authenticated');

create policy "Auth users manage attendance"
  on public.attendance_records for all
  using (auth.role() = 'authenticated')
  with check (auth.role() = 'authenticated');

create policy "Users manage own profile"
  on public.profiles for all
  using (auth.uid() = id)
  with check (auth.uid() = id);

create policy "Auth users read all profiles"
  on public.profiles for select
  using (auth.role() = 'authenticated');

create policy "Auth users manage sessions"
  on public.attendance_sessions for all
  using (auth.role() = 'authenticated')
  with check (auth.role() = 'authenticated');

create policy "Auth users manage sign ins"
  on public.session_sign_ins for all
  using (auth.role() = 'authenticated')
  with check (auth.role() = 'authenticated');

-- On signup: profile + student row (when role = student in metadata)
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  new_student_id bigint;
  user_role text;
  user_matric text;
  user_course text;
  user_name text;
begin
  user_role := coalesce(new.raw_user_meta_data->>'role', 'teacher');
  user_name := coalesce(new.raw_user_meta_data->>'full_name', split_part(new.email, '@', 1));
  user_matric := new.raw_user_meta_data->>'matric';
  user_course := coalesce(new.raw_user_meta_data->>'course', 'Computer Science');

  insert into public.profiles (id, full_name, role, matric, course)
  values (new.id, user_name, user_role, user_matric, user_course);

  if user_role = 'student' and user_matric is not null and length(trim(user_matric)) > 0 then
    insert into public.students (user_id, name, matric, course, email)
    values (new.id, user_name, trim(user_matric), user_course, new.email)
    returning id into new_student_id;

    update public.profiles
    set student_id = new_student_id
    where id = new.id;
  end if;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
